server {
  server_name actualbudget.homelab.cz;

  include /etc/nginx/conf.d/global.conf;


  set $upstream_actual http://actual-budget:5006;

  location ^~ /static/js/ {
    include snippets/authelia-protect.conf;
    proxy_pass $upstream_actual;
    include snippets/proxyHeader.conf;
    access_log off;
    log_not_found off;
  }

  location / {
    include snippets/authelia-protect.conf;
    proxy_pass $upstream_actual;
    include snippets/proxyHeader.conf;
  }
}

