server {
  server_name beszel.homelab.cz;

  include /etc/nginx/conf.d/global.conf;


  set $upstream_beszel http://beszel:8090;

  location ^~ /assets/ {
    include snippets/authelia-protect.conf;
    proxy_pass $upstream_beszel;
    include snippets/proxyHeader.conf;
    access_log off;
    log_not_found on;
  }

  location / {
    include snippets/authelia-protect.conf;
    proxy_pass $upstream_beszel;
    include snippets/proxyHeader.conf;

    proxy_read_timeout 360s;
  }
}

