server {
  server_name beszel.homelab.cz;

  include /etc/nginx/conf.d/global.conf;


  set $upstream_beszel http://beszel:8090;

  location / {
    proxy_pass $upstream_beszel;
    include snippets/proxyHeader.conf;

    proxy_read_timeout 360s;
  }
}

