server {
  server_name links.homelab.cz;

  include /etc/nginx/conf.d/global.conf;


  set $upstream_linkwarden http://linkwarden:3000;

  location ^~ /_next/static {
    include snippets/authelia-protect.conf;
    proxy_pass $upstream_linkwarden;
    include snippets/proxyHeader.conf;
    proxy_redirect off;
    access_log off;
    log_not_found on;
  }

  location / {
    include snippets/authelia-protect.conf;
    proxy_pass $upstream_linkwarden;
    include snippets/proxyHeader.conf;
  }
}

