server {
  server_name myadmin.homelab.cz;

  include /etc/nginx/conf.d/global.conf;


  set $upstream_myadmin http://myadmin:8080;

  location ^~ /static/js/ {
    include snippets/authelia-protect.conf;
    proxy_pass $upstream_myadmin;
    include snippets/proxyHeader.conf;
    proxy_redirect off;
    access_log off;
    log_not_found on;
  }

  location / {
    include snippets/authelia-protect.conf;
    proxy_pass $upstream_myadmin;
    include snippets/proxyHeader.conf;

    proxy_redirect off;
  }
}

