server {
  server_name vaultwarden.homelab.cz;

  include /etc/nginx/conf.d/global.conf;


  set $upstream_vault http://vaultwarden:80;

  location / {
    include snippets/authelia-protect.conf;
    proxy_pass $upstream_vault;
    include snippets/proxyHeader.conf;

    client_max_body_size 128M;
  }
}

