server {
  server_name vikunja.homelab.cz;

  include /etc/nginx/conf.d/global.conf;


  set $upstream_vikunja http://vikunja:3456;

  location /api/ {
    include snippets/authelia-protect.conf;
    proxy_pass $upstream_vikunja;
    include snippets/proxyHeader.conf;

    client_max_body_size 20M;
  }

  location ^~ /assets/ {
    include snippets/authelia-protect.conf;
    proxy_pass $upstream_vikunja;
    include snippets/proxyHeader.conf;
    access_log off;
    log_not_found on;
  }

  location / {
    include snippets/authelia-protect.conf;
    proxy_pass $upstream_vikunja;
    include snippets/proxyHeader.conf;

    client_max_body_size 20M;
  }

}
