server {
  server_name wakapi.homelab.cz;

  include /etc/nginx/conf.d/global.conf;

  set $upstream_wakapi http://wakapi:3000;

  location / {
    include snippets/authelia-protect.conf;
    proxy_pass $upstream_wakapi;
    include snippets/proxyHeader.conf;
  }
}

