server {
  server_name wakapi.homelab.cz;

  include /etc/nginx/conf.d/global.conf;

  set $upstream_wakapi http://wakapi:3000;

  location ^~ /assets/ {
    include snippets/authelia-protect.conf;
    proxy_pass $upstream_wakapi;
    include snippets/spa-cache.conf;
    access_log off;
    log_not_found on;
  }

  location ^~ /api/users/current/ {
    auth_request off;
    proxy_pass $upstream_wakapi;
    include snippets/proxyHeader.conf;
  }

  location / {
    include snippets/authelia-protect.conf;
    proxy_pass $upstream_wakapi;
    include snippets/proxyHeader.conf;
  }
}

