
set $upstream_beszel http://beszel:8090;

location /beszel/ {
  proxy_read_timeout 360s;
  proxy_http_version 1.1;
  include /etc/nginx/conf.d/proxyHeader.conf;

  rewrite /beszel/(.*) /$1 break;
  proxy_pass $upstream_beszel;
}
