
set $upstream_beszel http://beszel:8090;

location /beszel/ {
  include snippets/authelia-protect.conf;
  proxy_read_timeout 360s;
  include snippets/proxyHeader.conf;

  rewrite /beszel/(.*) /$1 break;
  proxy_pass $upstream_beszel;
}
