listen 8989 ssl;

port_in_redirect on;

set $target_encode_url $scheme://$http_host$request_uri;

include /etc/nginx/snippets/ssl.conf;
include snippets/authelia-auth.conf;
include /etc/nginx/conf.d/authelia.conf;
