
set $upstream_homepage http://homepage:3000;

location / {
  proxy_pass $upstream_homepage;
  include snippets/proxyHeader.conf;

  proxy_http_version 1.1;
  proxy_set_header Upgrade $http_upgrade;
  proxy_set_header Connection "upgrade";
}
