
set $upstream_myadmin http://myadmin:8080;

location /myadmin {
  include snippets/authelia-protect.conf;
  proxy_pass $upstream_myadmin;
  include snippets/proxyHeader.conf;

  proxy_redirect off;
}
