
set $upstream_vault http://vaultwarden:80;

location /vaultwarden/ {
  include snippets/authelia-protect.conf;
  proxy_pass $upstream_vault;
  include snippets/proxyHeader.conf;

  proxy_http_version 1.1;
  proxy_set_header Upgrade $http_upgrade;
  proxy_set_header Connection "upgrade";

  client_max_body_size 128M;
}
