location /vikunja/api/ {
  proxy_pass http://vikunja:3456/api/;
  include /etc/nginx/conf.d/proxyHeader.conf;

  proxy_http_version 1.1;
  proxy_set_header Upgrade $http_upgrade;
  proxy_set_header Connection "upgrade";

  client_max_body_size 20M;
}


location /vikunja/ {
  proxy_pass http://vikunja:3456;
  include /etc/nginx/conf.d/proxyHeader.conf;

  proxy_http_version 1.1;
  proxy_set_header Upgrade $http_upgrade;
  proxy_set_header Connection "upgrade";
  client_max_body_size 20M;
}
