
set $upstream_vikunja http://vikunja:3456;

location /vikunja/api/ {
  include snippets/authelia-protect.conf;
  rewrite ^/vikunja/(.*)$ /$1 break;
  proxy_pass $upstream_vikunja;
  include snippets/proxyHeader.conf;

  proxy_http_version 1.1;
  proxy_set_header Upgrade $http_upgrade;
  proxy_set_header Connection "upgrade";

  client_max_body_size 20M;
}


location /vikunja/ {
  include snippets/authelia-protect.conf;
  proxy_pass $upstream_vikunja;
  include snippets/proxyHeader.conf;

  proxy_http_version 1.1;
  proxy_set_header Upgrade $http_upgrade;
  proxy_set_header Connection "upgrade";
  client_max_body_size 20M;
}
