
set $upstream_vikunja http://vikunja:3456;

location /vikunja/api/ {
  include snippets/authelia-protect.conf;
  rewrite ^/vikunja/(.*)$ /$1 break;
  proxy_pass $upstream_vikunja;
  include snippets/proxyHeader.conf;

  client_max_body_size 20M;
}


location /vikunja/ {
  include snippets/authelia-protect.conf;
  proxy_pass $upstream_vikunja;
  include snippets/proxyHeader.conf;

  client_max_body_size 20M;
}
