
set $upstream_wakapi http://wakapi:3000;

location /wakapi/ {
  include snippets/authelia-protect.conf;
  rewrite ^/wakapi/(.*)$ /$1 break;
  proxy_pass $upstream_wakapi;
  include snippets/proxyHeader.conf;
}
