name: home-service

services:

  homepage:
    image: ghcr.io/gethomepage/homepage:latest
    container_name: homepage
    environment:
      - HOMEPAGE_ALLOWED_HOSTS=${ALLOWED_HOST}
      - PUID=${PUID}
      - PGID=${PGID}
    restart: unless-stopped
    volumes:
      - ./homepage/config:/app/config
      - /var/run/docker.sock:/var/run/docker.sock:ro
    depends_on:
      - wakapi
    networks:
      - homelab-internal

  wakapi:
    image: ghcr.io/muety/wakapi:latest
    container_name: wakapi
    environment:
      - /etc/localtime:/etc/localtime:ro
      - WAKAPI_BASE_PATH=/wakapi/
      - WAKAPI_DB_TYPE=postgres
      - WAKAPI_DB_HOST=postgres
      - WAKAPI_DB_PORT=5432
      - WAKAPI_DB_NAME=wakapi
      - WAKAPI_DB_USER=wakapi
      - WAKAPI_DB_PASSWORD_FILE=/run/secrets/wakapi_password
      #wakapi config
      - WAKAPI_LEADERBOARD_ENABLED=false
      - WAKAPI_PUBLIC_STATS=false
    secrets:
      - wakapi_password
    restart: unless-stopped
    networks:
      - homelab-internal
      - homelab-private

  vikunja:
    build:
      context: ./vikunja-repo
      dockerfile: Dockerfile
      args:
        - RELEASE_VERSION=v2.5.0
    container_name: vikunja
    environment:
      - VIKUNJA_SERVICE_ROOTURL=${BASE_URL}/vikunja/
      - VIKUNJA_SERVICE_PUBLICURL=${BASE_URL}/vikunja/
      - VIKUNJA_CORS_ENABLE=true
      - VIKUNJA_CORS_ORIGINS=${BASE_URL}/
      - VIKUNJA_DATABASE_HOST=postgres
      - VIKUNJA_DATABASE_TYPE=postgres
      - VIKUNJA_DATABASE_DATABASE=vikunja
      - VIKUNJA_DATABASE_USER=vikunja
      - VIKUNJA_DATABASE_PASSWORD_FILE=/run/secrets/vikunja_password
      - VIKUNJA_SERVICE_SECRET_FILE=/run/secrets/vikunja_secret
    volumes:
      - ./vikunja:/app/vikunja/files
      - /etc/localtime:/etc/localtime:ro
    secrets:
      - vikunja_password
      - vikunja_secret
    restart: unless-stopped
    networks:
      - homelab-internal
      - homelab-private
    healthcheck:
      test: ["CMD", "/app/vikunja/vikunja", "healthcheck"]
      interval: 30s
      timeout: 5s
      retries: 3

  vaultwarden:
    build: ./vaultwarden
    container_name: vaultwarden
    environment:
      - DOMAIN=${BASE_URL}/vaultwarden
      - SIGNUPS_ALLOWED=true
    volumes:
      - ./vault_data:/data
    secrets:
      - vaultwarden_db_password
    restart: unless-stopped
    networks:
      - homelab-internal
      - homelab-private

secrets:
  wakapi_password:
    file: .pswd/pswdwaka
  vikunja_password:
    file: .pswd/pswdvikunja
  vikunja_secret:
    file: .pswd/secretvin
  vaultwarden_db_password:
    file: .pswd/pswdvault

networks:
  homelab-internal:
    external: true
  homelab-private:
    external: true
