name: database

services:

  postgres:
    image: postgres@sha256:3a82e1f56c8f0f5616a11103ac3d47e632c3938698946a7ad26da0df1334744a
    container_name: Postgres
    restart: always
    ports:
     - "5432:5432"
    volumes:
      - /etc/localtime:/etc/localtime:ro
      - glob-database:/var/lib/postgresql
    environment:
      - POSTGRES_USER_FILE=/run/secrets/postgres_user
      - POSTGRES_PASSWORD_FILE=/run/secrets/postgres_password
    secrets:
      - postgres_user
      - postgres_password
    networks:
      - homelab-private
    healthcheck:
     test: ["CMD-SHELL", "pg_isready -q"]
     interval: 30s
     timeout: 5s
     retries: 3
     start_period: 15s

  myadmin:
    image: dpage/pgadmin4@sha256:2f4ce946ddf8360680d7eff4eaba1d91859eb6b4003e6623bad5c63a322c2f4d
    container_name: myadmin
    restart: unless-stopped
    volumes:
      - pdadmin-data:/var/lib/pgadmin
      - ${CERT_CRT}:/certs/proxy-ca.crt:ro
      - ./config/config_local.py:/pgadmin4/config_local.py:ro
      - /etc/localtime:/etc/localtime:ro
    environment:
      - REQUESTS_CA_BUNDLE=/certs/proxy-ca.crt
      - PGADMIN_DEFAULT_EMAIL=admin@valorant.com
      - PGADMIN_DEFAULT_PASSWORD_FILE=/run/secrets/email_password
      - PGADMIN_LISTEN_PORT=8080
      - PGADMIN_CONFIG_UPGRADE_CHECK_ENABLED=False
      - PGADMIN_CONFIG_ENHANCED_COOKIE_PROTECTION=False
      - PGADMIN_CONFIG_PROXY_X_FOR_COUNT=1
      - PGADMIN_CONFIG_PROXY_X_HOST_COUNT=1
      - PGADMIN_CONFIG_PROXY_X_PROTO_COUNT=1
      - PGADMIN_CONFIG_PROXY_X_PREFIX_COUNT=1
    secrets:
      - email_password
      - pgadmin_secret
    depends_on:
      - postgres
    networks:
      - homelab-internal
      - homelab-private
    healthcheck:
      test: ["CMD", "wget", "-qO-", "http://127.0.0.1:8080/misc/ping"]
      interval: 60s
      timeout: 5s
      retries: 3
      start_period: 30s

volumes:
  pdadmin-data:
  glob-database:

secrets:
  postgres_user:
    file: ./.pswd/user
  postgres_password:
    file: ./.pswd/pswdb
  email_password:
    file: ./.pswd/pswdmail
  pgadmin_secret:
    file: ./.pswd/pgadmin_secret

networks:
  homelab-internal:
    name: homelab-internal
    driver: bridge
    internal: true
  homelab-private:
    name: homelab-private
    driver: bridge
    internal: true
