- Applications:
    - Wakapi:
        icon: wakapi.png
        href: /wakapi/
        target: _self
- Admin:
    - pgAdmin:
        icon: pgadmin.png
        href: /myadmin/
        target: _blank
    - Immich:
        icon: immich.png
        url: https://homepage.local:8989/
    - Vaultwarden:
        icon: vaultwarden.png
        url: https://homepage.local:8989/
