- Applications:
    - Wakapi:
        icon: wakapi.png
        href: /wakapi/
        target: _blank
    - Vikunja:
        icon: vikunja.png
        href: /vikunja/
        target: _blank
    - Vaultwarden:
        icon: vaultwarden.png
        href: https://vaultwarden.homelab.cz:8989/
        target: _blank

- Monitoring:
    - Beszel:
        icon: beszel.png
        href: https://beszel.homelab.cz:8989/
        target: _blank

- Admin:
    - pgAdmin:
        icon: pgadmin.png
        href: https://myadmin.homelab.cz:8989/
        target: _blank
