- Applications:
    - Wakapi:
        icon: wakapi.png
        href: /wakapi/
        target: _self
    - Vikunja:
        icon: vikunja.png
        href: /vikunja/
        target: _self
    - Vaultwarden:
        icon: vaultwarden.png
        href: /vaultwarden/
        target: _self

- Monitoring:
    - Beszel:
        icon: beszel.png
        href: /beszel/
        target: _self

- Admin:
    - pgAdmin:
        icon: pgadmin.png
        href: https://myadmin.homelab.cz:8989/
        target: _blank
