---
# For configuration options and examples, please see:
# https://gethomepage.dev/configs/info-widgets/
- search:
    provider: duckduckgo
    target: _blank
    placeholder: Search...

- resources:
    cpu: false
    memory: false
    disk: false
    uptime: true
    expanded: true
    label: Homelab
