worker_processes 1;

events {
    worker_connections 1024;
}

http {

  proxy_headers_hash_max_size 1024;
  proxy_headers_hash_bucket_size 1024;

  log_format minimal '$remote_addr $time_local $request $status';
  server_tokens off;

  set_real_ip_from  10.0.0.0/8;
  set_real_ip_from  172.16.0.0/12;
  set_real_ip_from  192.168.0.0/16;
  set_real_ip_from  172.19.160.1;

  real_ip_header    X-Forwarded-For;
  real_ip_recursive on;

  resolver 127.0.0.11 valid=60s;

  server {
    listen 8989 ssl;
    server_name homelab;

    access_log /var/log/nginx/access.log minimal;
    ssl_certificate /etc/nginx/certs/homelab.crt;
    ssl_certificate_key /etc/nginx/certs/homelab.key;

    # Protocolos y cifrados recomendados
    ssl_protocols TLSv1.2 TLSv1.3;
    ssl_ciphers "HIGH:!aNULL:!MD5";
    # homepage
    include /etc/nginx/conf.d/homepage.conf;

    # Servicios
    include /etc/nginx/conf.d/wakapi.conf;
    include /etc/nginx/conf.d/myadmin.conf;
    include /etc/nginx/conf.d/vikunja.conf;
    include /etc/nginx/conf.d/vaultwarden.conf;

    # Monitoring
    include /etc/nginx/conf.d/beszel.conf;
  }
}

