worker_processes 1;

events {
    worker_connections 1024;
}

http {

  proxy_headers_hash_max_size 1024;
  proxy_headers_hash_bucket_size 1024;

  log_format minimal '$remote_addr $time_local $host $request $status';
  server_tokens off;

  set_real_ip_from  172.18.0.0/16;

  real_ip_header    X-Forwarded-For;
  real_ip_recursive on;

  resolver 127.0.0.11 valid=60s;

  access_log /var/log/nginx/access.log minimal;

  # Homepage
  include /etc/nginx/sites-enabled/homepage.conf;

  # Servicios
  include /etc/nginx/sites-enabled/wakapi.conf;
  include /etc/nginx/sites-enabled/vikunja.conf;
  include /etc/nginx/sites-enabled/vaultwarden.conf;
  include /etc/nginx/sites-enabled/actualbudget.conf;
  include /etc/nginx/sites-enabled/myadmin.conf;

  # Monitoring
  include /etc/nginx/sites-enabled/beszel.conf;
  include /etc/nginx/sites-enabled/drydock.conf;
}
