
access_control:
  default_policy: deny
  networks:
    - name: local_network
      networks:
        - 192.168.8.0/24
        - 172.16.0.0/12

  rules:
    - domain: 'homelab.cz'
      resources:
        # Homepage
        - '^/$'
      policy: bypass

    - domain: 'wakapi.homelab.cz'
      resources:
        - '^/.*$'
      networks:
        - local_network
      policy: bypass

    - domain: 'wakapi.homelab.cz'
      resources:
        - '^/.*$'
      policy: two_factor

    - domain: 'vikunja.homelab.cz'
      resources:
        - '^/.*$'
      networks:
        - local_network
      policy: bypass

    - domain: 'vikunja.homelab.cz'
      resources:
        - '^/.*$'
      policy: two_factor

    - domain: 'vaultwarden.homelab.cz'
      resources:
        - '^/.*$'
      networks:
        - local_network
      policy: bypass

    - domain: 'actualbudget.homelab.cz'
      resources:
        - '^/.*$'
      networks:
        - local_network
      policy: bypass

    - domain: 'actualbudget.homelab.cz'
      resources:
        - '^/.*$'
      policy: two_factor

    - domain: 'myadmin.homelab.cz'
      resources:
        - '^/.*$'
      networks:
        - local_network
      policy: bypass

    - domain: 'drydock.homelab.cz'
      resources:
        - '^/.*$'
      networks:
        - local_network
      policy: bypass

    - domain: 'beszel.homelab.cz'
      resources:
        - '^/.*$'
      networks:
        - local_network
      policy: bypass

