
access_control:
  default_policy: deny
  networks:
    - name: local_network
      networks:
        - 192.168.8.0/24
        - 172.16.0.0/12

  rules:
    - domain: 'homelab.cz'
      resources:
        # Homepage
        - '^/$'
      policy: bypass

    - domain: 'homelab.cz'
      resources:
        # Applications
        - '^/wakapi($|/.*)'
        - '^/vikunja($|/.*)'
        - '^/vaultwarden($|/.*)'
        # Monitoring
        - '^/beszel($|/.*)'
      networks:
        - local_network
      policy: bypass

    - domain: 'vaultwarden.homelab.cz'
      resources:
        - '^/.*$'
      networks:
        - local_network
      policy: bypass

    - domain: 'myadmin.homelab.cz'
      resources:
        - '^/.*$'
      networks:
        - local_network
      policy: bypass

    - domain: 'beszel.homelab.cz'
      resources:
        - '^/.*$'
      networks:
        - local_network
      policy: bypass

    - domain: 'homelab.cz'
      resources:
        #Applications
        - '^/wakapi($|/.*)'
        - '^/vikunja($|/.*)'
        - '^/vaultwarden($|/.*)'
        # Monitoring
        - '^/beszel($|/.*)'
      policy: two_factor
