
server:
  address: 'tcp://0.0.0.0:9091/authelia'
  buffers:
    read: 4096
    write: 4096

notifier:
  disable_startup_check: false
  filesystem:
    filename: /config/notification.txt

session:
  name: authelia_session
  expiration: '1h'
  inactivity: '15m'
  cookies:
    - domain: 'homelab.cz'
      authelia_url: 'https://homelab.cz:8989/authelia'
      default_redirection_url: 'https://homelab.cz:8989/'

storage:
  postgres:
    address: 'tcp://postgres:5432'
    database: authelia_db
    username: authelia
    timeout: 5s
